DROP TABLE IF EXISTS `personID`;
DROP TABLE IF EXISTS `security`;
DROP TABLE IF EXISTS `hashes`;
DROP TABLE IF EXISTS `permissions`;
DROP TABLE IF EXISTS `verifications`;
DROP TABLE IF EXISTS `device`;

CREATE TABLE personID(
    walletID TEXT NOT NULL DEFAULT '' PRIMARY KEY ON CONFLICT IGNORE,
    userID TEXT NOT NULL DEFAULT '',
    photo BLOB NOT NULL,
    fn TEXT NOT NULL DEFAULT '',
    mn TEXT NOT NULL DEFAULT '',
    sn TEXT NOT NULL DEFAULT '',
    nin TEXT NOT NULL DEFAULT '',
    DoB DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    CENTRAL_RECORD_ID TEXT NOT NULL DEFAULT '',
    idNumber TEXT NOT NULL DEFAULT '' UNIQUE,
    MRZ1 TEXT NOT NULL DEFAULT '',
    MRZ2 TEXT NOT NULL DEFAULT '',
    MRZ3 TEXT NOT NULL DEFAULT '',
    HASH TEXT NOT NULL DEFAULT ''
);

CREATE TABLE security(
    userID TEXT NOT NULL DEFAULT '' PRIMARY KEY ON CONFLICT IGNORE,
    username TEXT NOT NULL DEFAULT '',
    password TEXT NOT NULL DEFAULT '',
    pubKey  TEXT NOT NULL DEFAULT ''
);

CREATE TABLE hashes(
    userID TEXT NOT NULL DEFAULT '' PRIMARY KEY ON CONFLICT IGNORE,
    B TEXT NOT NULL DEFAULT '',
    L1 TEXT NOT NULL DEFAULT '',
    L2 TEXT NOT NULL DEFAULT '',
    L3 TEXT NOT NULL DEFAULT '',
    N TEXT NOT NULL DEFAULT '',
    F TEXT NOT NULL DEFAULT ''
);

CREATE TABLE device(
    userID TEXT NOT NULL DEFAULT '' PRIMARY KEY ON CONFLICT IGNORE,
    idNumber TEXT NOT NULL DEFAULT '' UNIQUE,
    deviceID TEXT NOT NULL DEFAULT '' UNIQUE,
    deviceCount INT NOT NULL DEFAULT 1
);

CREATE TABLE verifications(
    userID TEXT NOT NULL DEFAULT '' PRIMARY KEY ON CONFLICT IGNORE,
    idNumber TEXT NOT NULL DEFAULT '' UNIQUE,
    DATE DATE NOT NULL,
    verifierID TEXT NOT NULL DEFAULT '',
    vType TEXT NOT NULL DEFAULT '' ,
    vStatus TEXT NOT NULL DEFAULT ''
);

CREATE TABLE permissions(
    id INT AUTO_INCREMENT NOT NULL,
    userID TEXT NOT NULL DEFAULT '',
    permissionType TEXT NOT NULL DEFAULT '',
    ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

